# Generated by Django 6.0.7 on 2026-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearchprofile',
            name='last_searched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
